package templates_test

import (
	"bytes"
	"testing"
	"text/template"

	"github.com/adamkali/egg_cli/pkg/templates"
)

const ResultCONTROLLER_ControllerTemplate = `
/* Generated by egg v0.0.1 */

package controllers

import (
	"context"

	"github.com/adamkali/egg/cmd/configuration"
	"github.com/adamkali/egg/middlwares/configs"
	"github.com/adamkali/egg/services"
	"github.com/jackc/pgx/v5/pgxpool"
	"github.com/labstack/echo/v4"
	echojwt "github.com/labstack/echo-jwt/v4"
)

type Registrar struct {
	Config           *configuration.Configuration
	ValidatorService *services.ValidatorService
	UserService      services.IUserService
	AuthService      services.IAuthService
	MinioService     services.IMinioService
	RedisService     services.IRedisService
}

type IController interface {
	Attatch(e *echo.Echo, authMiddleware echo.MiddlewareFunc)
}

func createControllerParams(config *configuration.Configuration) (*Registrar, error) {
	ctx := context.Background()
	db, err := pgxpool.New(ctx, config.Database.URL)
	if err != nil {
		return nil, err
	}

	return &Registrar{
		Config:           config,
		ValidatorService: &services.ValidatorService{},
		AuthService:      services.CreateAuthService(ctx, db, config),
		UserService:      services.CreateUserService(ctx, db),
		MinioService:     services.CreateMinioService(ctx, config),
		RedisService:     services.CreateRedisService(ctx, config),
	}, nil
}

func AttatchControllers(e *echo.Echo, config *configuration.Configuration, conts ...IController) {
	// configure middlewares here right now it is just an authentication
	for _, v := range conts {
		v.Attatch(e, echojwt.WithConfig(configs.AuthMiddlewareConfig(config)))
	}
}
`

func TestCONTROLLER_ControllerTemplate(t *testing.T) {
	// load the template
	temp := templates.CONTROLLER_ControllerTemplate
	templateTest := template.Must(template.New("controller.go").Parse(temp))

	// execute the template
	stringWriter := new(bytes.Buffer)
	err := templateTest.ExecuteTemplate(stringWriter, "controller.go", createConfiguration())
	if err != nil {
		t.Error(err)
	}

	// check the result
	if stringWriter.String() != ResultCONTROLLER_ControllerTemplate {
		diff := Diff(stringWriter.String(), ResultCONTROLLER_ControllerTemplate)
		for i, v := range diff {
			t.Errorf("line %d: expected %s, got %s", i, v.Expected, v.Actual)
		}
	}
}
