package templates_test

import (
	"bytes"
	"testing"
	"text/template"

	"github.com/adamkali/egg_cli/pkg/templates"
)

const ResultDATABASE_QUERIES_TokenTemplate = `
-- Generated by egg v0.0.1


-- name: FindTokenByToken :one
SELECT *
    FROM tokens 
    WHERE token = $1
    AND  expiration_datetime > now();

-- name: FindTokenByUserId :one
SELECT *
    FROM tokens 
    WHERE user_id = $1
    AND  expiration_datetime > now();

-- name: UpdateTokenByUserId :exec
UPDATE tokens 
    SET token = $1, expiration_datetime = $2
    WHERE user_id = $3;

-- name: CreateToken :one
INSERT INTO tokens (
    user_id, expiration_datetime, token
) VALUES ( $1, $2, $3 )
RETURNING *;
`

func TestDATABASE_QUERIES_TokenTemplate(t *testing.T) {
	temp := templates.DATABASE_QUERIES_TokenTemplate
	templateTest := template.Must(template.New("token_queries.sql").Parse(temp))

	stringWriter := new(bytes.Buffer)
	err := templateTest.ExecuteTemplate(stringWriter, "token_queries.sql", createConfiguration())
	if err != nil {
		t.Error(err)
	}

	if stringWriter.String() != ResultDATABASE_QUERIES_TokenTemplate {
		diff := Diff(stringWriter.String(), ResultDATABASE_QUERIES_TokenTemplate)
		for i, v := range diff {
			t.Errorf("line %d: expected %s, got %s", i, v.Expected, v.Actual)
		}
	}
}
