package templates_test

import (
	"bytes"
	"testing"
	"text/template"

	"github.com/adamkali/egg_cli/pkg/templates"
)

const ResultDockerignoreTemplate = `
# Generated by egg v0.0.1

# If you prefer the allow list template instead of the deny list, see community template:
# https://github.com/github/gitignore/blob/main/community/Golang/Go.AllowList.gitignore
#
# Binaries for programs and plugins
*.exe
*.exe~
*.dll
*.so
*.dylib

# Test binary, built with ` + "`go test -c`" + `
*.test

# Output of the go coverage tool, specifically when used with LiteIDE
*.out

# Dependency directories (remove the comment below to include it)
# vendor/
wiki/
.git/
.github/
.vscode/

# Go workspace file
go.work
go.work.sum
Dockerfile
.dockerignore
node_modules
npm-debug.log
README.md
.next
.git

tmp/

`

func TestDockerignoreTemplate(t *testing.T) {
	// load the template
	temp := templates.DockerignoreTemplate
	templateTest := template.Must(template.New(".dockerignore").Parse(temp))

	// execute the template
	stringWriter := new(bytes.Buffer)
	err := templateTest.ExecuteTemplate(stringWriter, ".dockerignore", createConfiguration())
	if err != nil {
		t.Error(err)
	}

	// check the result
	if stringWriter.String() != ResultDockerignoreTemplate {
		diff := Diff(stringWriter.String(), ResultDockerignoreTemplate)
		for i, v := range diff {
			t.Errorf("line %d: expected %s, got %s", i, v.Expected, v.Actual)
		}
	}
}
