package templates_test

import (
	"bytes"
	"testing"
	"text/template"

	"github.com/adamkali/egg_cli/pkg/templates"
)

const ResultMainGoTemplate = `
/* Generated by egg v0.0.1

Copyright © 2022 Adam Kalinowski  

This is made by the Full Stack Template
*/
package main

import (
	"github.com/adamkali/egg/cmd"
)

// @Title egg 
// @Version 0.0.1
// @Description This is the swagger page for the Project egg generated with Egg-go. use this to test your database connection
// @Contact.name Adam Kalinowski 
// @Contact.url https://github.com/adamkali/egg
// @License.name Apache-2.0
// @BasePath /api
func main() {
	cmd.Execute()
}
`

func TestMainGoTemplate(t *testing.T) {
	// load the template
	temp := templates.MainGoTemplate
	templateTest := template.Must(template.New("main.go").Parse(temp))

	// execute the template
	stringWriter := new(bytes.Buffer)
	err := templateTest.ExecuteTemplate(stringWriter, "main.go", createConfiguration())
	if err != nil {
		t.Error(err)
	}

	// check the result
	if stringWriter.String() != ResultMainGoTemplate {
		diff := Diff(stringWriter.String(), ResultMainGoTemplate)
		for i, v := range diff {
			t.Errorf("line %d: expected %s, got %s", i, v.Expected, v.Actual)
		}
	}
}
