package templates_test

import (
	"bytes"
	"testing"
	"text/template"

	"github.com/adamkali/egg_cli/pkg/templates"
)

const ResultMakefileTemplate = `
# Generated by egg v0.0.1
# build-tailwindcss: # this is if you want to render your frontend
#   on the server without React 
# 	tailwindcss -i ./tailwind.css -o ./public/css/index.css 
build-backend:
	go build -o ./tmp/egg .
build-frontend: 
	cd ./frontend/ && pnpm format && pnpm build
build-swagger:
	./tmp/egg swag
build: build-backend build-swagger build-frontend
`

func TestMakefileTemplate(t *testing.T) {
	// load the template
	temp := templates.MakefileTemplate
	templateTest := template.Must(template.New("Makefile").Parse(temp))

	// execute the template
	stringWriter := new(bytes.Buffer)
	err := templateTest.ExecuteTemplate(stringWriter, "Makefile", createConfiguration())
	if err != nil {
		t.Error(err)
	}

	// check the result
	if stringWriter.String() != ResultMakefileTemplate {
		diff := Diff(stringWriter.String(), ResultMakefileTemplate)
		for i, v := range diff {
			t.Errorf("line %d: expected %s, got %s", i, v.Expected, v.Actual)
		}
	}
}
