package templates

const MODELS_REQUESTS_LoginRequestTemplate = `
/* Generated by egg v0.0.1 */

package requests

type LoginRequest struct {
	Username string ` + "`" +`json:"username"` + "`" +`
	Email    string ` + "`" +`json:"email"` + "`" +`
	Password string ` + "`" +`json:"password"` + "`" +`
} // @name LoginRequest

`
