package templates_test

import (
	"bytes"
	"testing"
	"text/template"

	"github.com/adamkali/egg_cli/pkg/templates"
)

const ResultMODELS_HANDLERS_LoginHandlerTemplate = `
/* Generated by egg v0.0.1 */

package handlers

import (
	"fmt"

	"github.com/adamkali/egg/internal/repository"
	"github.com/adamkali/egg/models/requests"
	"github.com/adamkali/egg/models/responses"
	"github.com/labstack/echo/v4"
)

type LoginHandler struct {
	Context       echo.Context
	Request       *requests.LoginRequest
	Authenticated *repository.User
	Token         *string
	Error         error
	Code          int
	Locked        bool
}

func NewLoginFormHandler(
	ctx echo.Context,
) *LoginHandler {
	handler := &LoginHandler{Locked: false, Context: ctx}
	return handler
}

func (h *LoginHandler) Handler(i any) *LoginHandler {
	var code int
	if !h.Locked {
		switch handler := i.(type) {
		case func(req repository.User) (*string, error):
			code = 500
			h.Token, h.Error = handler(*h.Authenticated)
		case func(*requests.LoginRequest) (*repository.User, error):
			code = 401
			h.Authenticated, h.Error = handler(h.Request)
			fmt.Printf("authenticate %v\n", h.Authenticated)
			if h.Authenticated == nil {
				h.Error = echo.NewHTTPError(code, "Request parameters could not find a user")
			}
		case func(e echo.Context) (*requests.LoginRequest, error):
			code = 400
			h.Request, h.Error = handler(h.Context)
		default:
			fmt.Printf("Type assertion failed for type: %T\n", i)
			code = 600
			h.Error = echo.NewHTTPError(code, "Misaligned handler on the server")
		}
		if h.Error != nil {
			return h.Lock(code)
		}
	}
	return h
}

func (h *LoginHandler) Lock(code int) *LoginHandler {
	h.Locked = true
	h.Code = code
	return h
}

func (h *LoginHandler) JSON() error {
	var code int
	var message string
	var jwt string
	if h.Token == nil {
		jwt = ""
	} else {
		jwt = *h.Token
	}
	if h.Locked && h.Error != nil {
		code = h.Code
		if code == 600 {
			message = "Misaligend handler on the server"
		} else {
			message = h.Error.Error()
		}
	} else {
		message = "OK"
		code = 200
	}
	return h.Context.JSON(code, responses.LoginResponse{
		Data:    responses.UserDataFromRepository(h.Authenticated),
		Success: !h.Locked,
		Message: message,
		JWT:     jwt,
	})
}

func (h *LoginHandler) Render() error {
	if h.Locked {
		return h.JSON()
	}
	return h.Context.Redirect(200, "/users/dashboard/"+h.Authenticated.ID.String())
}
`

func TestMODELS_HANDLERS_LoginHandlerTemplate(t *testing.T) {
	// load the template
	temp := templates.MODELS_HANDLERS_LoginHandlerTemplate
	templateTest := template.Must(template.New("login_handler.go").Parse(temp))

	// execute the template
	stringWriter := new(bytes.Buffer)
	err := templateTest.ExecuteTemplate(stringWriter, "login_handler.go", createConfiguration())
	if err != nil {
		t.Error(err)
	}

	// check the result
	if stringWriter.String() != ResultMODELS_HANDLERS_LoginHandlerTemplate {
		diff := Diff(stringWriter.String(), ResultMODELS_HANDLERS_LoginHandlerTemplate)
		for i, v := range diff {
			t.Errorf("line %d: expected %s, got %s", i, v.Expected, v.Actual)
		}
	}
}
