package templates

const MODELS_REQUESTS_NewUserRequestTemplate = `
/* Generated by egg v0.0.1 */

package requests

type NewUserRequest struct {
	Username string ` + "`" +`json:"username"` + "`" +`
	Email    string ` + "`" +`json:"email"` + "`" +`
	Password string ` + "`" +`json:"password"` + "`" +`
	IsAdmin  bool   ` + "`" +`json:"isAdmin"` + "`" +`
} // @name NewUserRequest

`
