package templates

const SERVICES_IAuthServiceTemplate = `
/* Generated by egg v0.0.1 */

package services

import (
	"{{.Namespace}}/{{.Database.SqlcRepositoryLocation}}"
)


type IAuthService interface {
	Create(user *repository.User) (*string, error)
 	Update(user repository.User) (*string, error)
	CheckToken(token string) error
}
`
