failed:
    moduleName: egg::rsbuild_frontend
    error: 'exec: "pnpm create rsbuild@latest": executable file not found in $PATH'
succeeded:
    - egg::initialize
    - egg::install_tools
    - egg::install_libraries
    - egg::bootstrap_directories
    - egg::generate_configuration
    - egg::bootstrap_framwork
configuration:
    namespace: github.com/adamkali/egg-app
    name: egg-app
    semver: 0.0.1
    license: MIT
    copyright:
        year: 2025
        author: adamkali
    server:
        jwt: hZiObSwyb2MXzKeYKbITaBKVq42LfgLoctfeZ6eH9Zk=
        port: 8080
        frontend:
            dir: web/dist
            api: web/src/api
    database:
        url: postgres://postgres@localhost:5432/egg?sslmode=disable
        sqlc: sql
        repository: db/repository
        queries: db/queries
        migration:
            protocol: postgresql
            destination: db/migrations
    cache:
        url: redis://localhost:6379
    s3:
        url: localhost:8555
        access: v6QZBVSWLeAZCTa6wVjJh+6Ae0D5Xhj67xp5u7yuhJY=
        secret: NAC+3K191tYqHikxK4H1VbWMy8EuEzNEnwHd44Vbuo0=
