
/* Generated by egg v0.0.1

Copyright © 2025 adamkali  

This is made by the Full Stack Template
*/
package main

import (
	"github.com/adamkali/egg-app/cmd"
)

// @Title egg-app 
// @Version 0.0.1
// @Description This is the swagger page for the Project egg-app generated with Egg-go. use this to test your database connection
// @Contact.name Adam Kalinowski 
// @Contact.url https://github.com/adamkali/egg-app
// @License.name MIT
// @BasePath /api
func main() {
	cmd.Execute()
}
