
/* Generated by egg v0.0.1

Copyright © 2024 Test User  

This is made by the Full Stack Template
*/
package main

import (
	"github.com/testuser/testproject/cmd"
)

// @Title testproject 
// @Version 0.0.1
// @Description This is the swagger page for the Project testproject generated with Egg-go. use this to test your database connection
// @Contact.name Adam Kalinowski 
// @Contact.url https://github.com/testuser/testproject
// @License.name MIT
// @BasePath /api
func main() {
	cmd.Execute()
}
